export const cardList = [
  {
    id: 1,
    topic: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 2,
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 3,
    topic: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 4,
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "В работе",
  },
  {
    id: 5,
    topic: "Copywriting",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 6,
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 7,
    topic: "Copywriting",
    title: "Название задачи",
    date: "30.10.23",
    status: "В работе",
  },
  {
    id: 8,
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "Готово",
  },
  {
    id: 9,
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "Тестирование",
  },
  {
    id: 10,
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "Нужно сделать",
  },
  {
    id: 11,
    topic: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    status: "В работе",
  },
];

export const statusList = [
  "Без статуса",
  "Нужно сделать",
  "В работе",
  "Тестирование",
  "Готово",
];
